# Generated by Django 4.1.7 on 2023-06-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('citilink_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regard_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerCase',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('form_factor', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('capacity', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('socket', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('wattage', models.IntegerField()),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('socket', models.CharField(max_length=50)),
                ('cores', models.IntegerField()),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('capacity', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('capacity', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apppc.component')),
                ('memory_capacity', models.CharField(max_length=50)),
                ('memory_type', models.CharField(max_length=50)),
                ('memory_clock', models.CharField(max_length=50)),
            ],
            bases=('apppc.component',),
        ),
        migrations.AddField(
            model_name='component',
            name='prices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppc.price'),
        ),
    ]
