# Generated by Django 4.1.7 on 2023-06-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='citilink_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='dns_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='regard_price',
            field=models.CharField(max_length=100),
        ),
    ]
