# Generated by Django 4.1.7 on 2023-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppc', '0002_alter_component_details_alter_price_citilink_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
