# Generated by Django 4.1.7 on 2023-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppc', '0005_alter_component_details_alter_component_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='details',
            field=models.CharField(max_length=300),
        ),
    ]
