# Generated by Django 4.1.7 on 2023-06-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppc', '0006_alter_component_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='wattage',
            field=models.CharField(max_length=10),
        ),
    ]
