# Generated by Django 4.1.7 on 2023-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppc', '0007_alter_powersupply_wattage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='citilink_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='dns_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='regard_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
